name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ python3
      - name: Configure
        run: cmake --preset dev
      - name: Build
        run: cmake --build --preset dev --parallel
      - name: Test
        run: ctest --preset dev --output-on-failure
